version: 2.1

executors:
  main-executor:
    docker:
      - image: circleci/node:lts

jobs:
  install-dependencies:
    executor: main-executor
    steps:
      - checkout
      - run: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  quality-check:
    executor: main-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run prettier:check

  test:
    executor: main-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run test

  deploy:
    executor: main-executor
    parameters:
      clever-app-id:
        type: string
    steps:
      - checkout
      - run: |
          sudo npm install --global clever-tools
          clever login --token=$CLEVER_TOKEN --secret=$CLEVER_SECRET
          clever link << parameters.clever-app-id >>
          clever deploy --force

workflows:
  version: 2

  deploy:
    jobs:
      - install-dependencies:
          filters:
            tags:
              only: /.*/
      - quality-check:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - deploy:
          clever-app-id: app_b2928a5b-2ffd-41d9-b15f-3d3ee3d779dc
          requires:
            - quality-check
            - test
          context: clever-cloud2-zenika-dev
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
